### ISSUE TITLE
Docker interactions with latest Ubuntu 24.04

### ISSUE THREAD

**Issue by vzoutenbier** [davestephens/ansible-nas#709]
**Describe the bug**
I am running into issues running the playbook after a clean install of Ubuntu 24.04, and following Ansible + ansible-nas install instructions.  Errors occur at: 

- ctop not found
- Remove docker-py python module
- Install docker python module
(got no further)

**Environment**
- Ansible-NAS revision (`git rev-parse --short HEAD`): a4773cf6
- Ansible version (paste the entire output of `ansible --version` on the machine you run the playbook from):
ansible [core 2.16.7]
  config file = /home/vincent/ansible-nas/ansible.cfg
  configured module search path = ['/home/vincent/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/vincent/.local/share/pipx/venvs/ansible/lib/python3.12/site-packages/ansible
  ansible collection location = /home/vincent/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/vincent/.local/bin/ansible
  python version = 3.12.3 (main, Apr 10 2024, 05:33:47) [GCC 13.2.0] (/home/vincent/.local/share/pipx/venvs/ansible/bin/python)
  jinja version = 3.1.4
  libyaml = True

- Ansible-NAS operating system (`cat /etc/lsb-release` on the Ansible-NAS box) - _Support won't be provided for non-LTS releases of Ubuntu_: DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=24.04
DISTRIB_CODENAME=noble
DISTRIB_DESCRIPTION="Ubuntu 24.04 LTS"

- Ansible-NAS kernel (`uname -a` on the Ansible-NAS box): Linux ansible-nas 6.8.0-31-generic #31-Ubuntu SMP PREEMPT_DYNAMIC Sat Apr 20 00:40:06 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

- Ansible-NAS Python version (`python**3** --version` on the Ansible-NAS box):
Python 3.12.3

- Ansible-NAS Docker version (`docker --version` on the Ansible-NAS box): 
Docker version 26.1.3, build b72abbb

- Latest Docker logs (`journalctl -u docker.service` on the Ansible-NAS box):
- -- Boot 5191f506d357486fa6ec9451014e03ba --
May 25 00:59:07 kronk systemd[1]: Starting docker.service - Docker Application Container Engine...
May 25 00:59:08 kronk dockerd[1159]: time="2024-05-24T22:59:08.175742856Z" level=info msg="Starting up"
May 25 00:59:08 kronk dockerd[1159]: time="2024-05-24T22:59:08.181508702Z" level=info msg="detected 127.0>
May 25 00:59:08 kronk dockerd[1159]: time="2024-05-24T22:59:08.294499671Z" level=info msg="[graphdriver] >
May 25 00:59:08 kronk dockerd[1159]: time="2024-05-24T22:59:08.296720588Z" level=info msg="Loading contai>
May 25 00:59:08 kronk dockerd[1159]: time="2024-05-24T22:59:08.770559088Z" level=info msg="Default bridge>
May 25 00:59:08 kronk dockerd[1159]: time="2024-05-24T22:59:08.920990411Z" level=info msg="Loading contai>
May 25 00:59:08 kronk dockerd[1159]: time="2024-05-24T22:59:08.950607825Z" level=info msg="Docker daemon">

- Are you running the playbook from a remote box or the Ansible-NAS box itself? 
box itself

- Vagrant version, if testing (`vagrant --version`):
- Ansible-NAS filesystems (`df -hT` on the Ansible-NAS box):
- Mounted filesystems (`mount` on the Ansible-NAS box)

**all.yml Variables**
defaults
- `docker_image_directory`:
- `docker_home`:
- `docker_storage_driver`:
- `samba_shares_root`:

**Expected behavior**
The playbook should run all the way through.

**Actual behavior**
I get an error, and cannot track down the ctop package anywhere in apt.

bypassing that by commenting out ctop requirement, I get an error at 'Remove docker-py python module'

**Steps to reproduce**
Clean install of Ubuntu LTS (desktop OR server)
Install ssh access
Install ansible according to website
Install ansible-nas according to install instructions

adjust ansible-nas/inventories/kronk/group_vars/nas.yml with: 

ansible_nas_hostname: ansible-nas
ansible_nas_timezone: Europe/Amsterdam

ansible_nas_user: Vincent
ansible_nas_email: *@gmail.com
ansible_nas_domain: *.com

homepage_enabled: true

samba_shares_root: /mnt/Data0
samba_server_string: Kronk

 call : ansible-playbook -i inventories/ansible-nas/inventory nas.yml -b -K from ansible-nas dir.

--> ctop error 
Bypass by commenting ctop to continue, 

error in "Remove docker-py python module"

**Playbook Output**

## ctop error:

/// <localhost> EXEC /bin/sh -c 'echo ~vincent && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/vincent/.ansible/tmp `"&& mkdir "` echo /home/vincent/.ansible/tmp/ansible-tmp-1716593323.7409317-19746-263048265079323 `" && echo ansible-tmp-1716593323.7409317-19746-263048265079323="` echo /home/vincent/.ansible/tmp/ansible-tmp-1716593323.7409317-19746-263048265079323 `" ) && sleep 0'
Using module file /home/vincent/.local/share/pipx/venvs/ansible/lib/python3.12/site-packages/ansible/modules/apt.py
<localhost> PUT /home/vincent/.ansible/tmp/ansible-local-18486ed1du23y/tmp1knpifla TO /home/vincent/.ansible/tmp/ansible-tmp-1716593323.7409317-19746-263048265079323/AnsiballZ_apt.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/vincent/.ansible/tmp/ansible-tmp-1716593323.7409317-19746-263048265079323/ /home/vincent/.ansible/tmp/ansible-tmp-1716593323.7409317-19746-263048265079323/AnsiballZ_apt.py && sleep 0'
<localhost> EXEC /bin/sh -c 'sudo -H -S -p "[sudo via ansible, key=rlutyhvzftztrfsynhiapzfhldrshvun] password:" -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-rlutyhvzftztrfsynhiapzfhldrshvun ; /usr/bin/python3 /home/vincent/.ansible/tmp/ansible-tmp-1716593323.7409317-19746-263048265079323/AnsiballZ_apt.py'"'"' && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /home/vincent/.ansible/tmp/ansible-tmp-1716593323.7409317-19746-263048265079323/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
  File "/tmp/ansible_ansible.builtin.apt_payload_7tjq3q8j/ansible_ansible.builtin.apt_payload.zip/ansible/modules/apt.py", line 533, in package_status
    pkg = cache[pkgname]
          ~~~~~^^^^^^^^^
  File "/usr/lib/python3/dist-packages/apt/cache.py", line 279, in __getitem__
    raise KeyError("The cache has no package named %r" % key)
fatal: [ansible-nas]: FAILED! => {
    "attempts": 3,
    "changed": false,
    "invocation": {
        "module_args": {
            "allow_change_held_packages": false,
            "allow_downgrade": false,
            "allow_unauthenticated": false,
            "autoclean": false,
            "autoremove": false,
            "cache_valid_time": 0,
            "clean": false,
            "deb": null,
            "default_release": null,
            "dpkg_options": "force-confdef,force-confold",
            "fail_on_autoremove": false,
            "force": false,
            "force_apt_get": false,
            "install_recommends": null,
            "lock_timeout": 60,
            "name": [
                "smartmontools",
                "htop",
                "zfsutils-linux",
                "bonnie++",
                "unzip",
                "lm-sensors",
                "ctop"
            ],
            "only_upgrade": false,
            "package": [
                "smartmontools",
                "htop",
                "zfsutils-linux",
                "bonnie++",
                "unzip",
                "lm-sensors",
                "ctop"
            ],
            "policy_rc_d": null,
            "purge": false,
            "state": "present",
            "update_cache": null,
            "update_cache_retries": 5,
            "update_cache_retry_max_delay": 12,
            "upgrade": null
        }
    },
    "msg": "No package matching 'ctop' is available"
}

PLAY RECAP ***********************************************************************************************
ansible-nas                : ok=30   changed=0    unreachable=0    failed=1    skipped=33   rescued=0    ignored=0   \\\

## Remove docker error output:

\\\ FAILED - RETRYING: [ansible-nas]: Remove docker-py python module (1 retries left).Result was: {
    "attempts": 3,
    "changed": false,
    "cmd": [
        "/usr/bin/python3",
        "-m",
        "pip.__main__",
        "uninstall",
        "-y",
        "docker-py"
    ],
    "invocation": {
        "module_args": {
            "chdir": null,
            "editable": false,
            "executable": null,
            "extra_args": null,
            "name": [
                "docker-py"
            ],
            "requirements": null,
            "state": "absent",
            "umask": null,
            "version": null,
            "virtualenv": null,
            "virtualenv_command": "virtualenv",
            "virtualenv_python": null,
            "virtualenv_site_packages": false
        }
    },
    "msg": "\n:stderr: error: externally-managed-environment\n\n× This environment is externally managed\n╰─> To install Python packages system-wide, try apt install\n    python3-xyz, where xyz is the package you are trying to\n    install.\n    \n    If you wish to install a non-Debian-packaged Python package,\n    create a virtual environment using python3 -m venv path/to/venv.\n    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make\n    sure you have python3-full installed.\n    \n    If you wish to install a non-Debian packaged Python application,\n    it may be easiest to use pipx install xyz, which will manage a\n    virtual environment for you. Make sure you have pipx installed.\n    \n    See /usr/share/doc/python3.12/README.venv for more information.\n\nnote: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.\nhint: See PEP 668 for the detailed specification.\n",
    "retries": 4
}
<localhost> EXEC /bin/sh -c 'echo ~vincent && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/vincent/.ansible/tmp `"&& mkdir "` echo /home/vincent/.ansible/tmp/ansible-tmp-1716593557.178456-21842-205803354970467 `" && echo ansible-tmp-1716593557.178456-21842-205803354970467="` echo /home/vincent/.ansible/tmp/ansible-tmp-1716593557.178456-21842-205803354970467 `" ) && sleep 0'
Using module file /home/vincent/.local/share/pipx/venvs/ansible/lib/python3.12/site-packages/ansible/modules/pip.py
<localhost> PUT /home/vincent/.ansible/tmp/ansible-local-20037ubefxai7/tmpxrfkjgdf TO /home/vincent/.ansible/tmp/ansible-tmp-1716593557.178456-21842-205803354970467/AnsiballZ_pip.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/vincent/.ansible/tmp/ansible-tmp-1716593557.178456-21842-205803354970467/ /home/vincent/.ansible/tmp/ansible-tmp-1716593557.178456-21842-205803354970467/AnsiballZ_pip.py && sleep 0'
<localhost> EXEC /bin/sh -c 'sudo -H -S -p "[sudo via ansible, key=oxxdfkkylurdkxyosohijoqbkedfrlfk] password:" -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-oxxdfkkylurdkxyosohijoqbkedfrlfk ; /usr/bin/python3 /home/vincent/.ansible/tmp/ansible-tmp-1716593557.178456-21842-205803354970467/AnsiballZ_pip.py'"'"' && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /home/vincent/.ansible/tmp/ansible-tmp-1716593557.178456-21842-205803354970467/ > /dev/null 2>&1 && sleep 0'
fatal: [ansible-nas]: FAILED! => {
    "attempts": 3,
    "changed": false,
    "cmd": [
        "/usr/bin/python3",
        "-m",
        "pip.__main__",
        "uninstall",
        "-y",
        "docker-py"
    ],
    "invocation": {
        "module_args": {
            "chdir": null,
            "editable": false,
            "executable": null,
            "extra_args": null,
            "name": [
                "docker-py"
            ],
            "requirements": null,
            "state": "absent",
            "umask": null,
            "version": null,
            "virtualenv": null,
            "virtualenv_command": "virtualenv",
            "virtualenv_python": null,
            "virtualenv_site_packages": false
        }
    },
    "msg": "\n:stderr: error: externally-managed-environment\n\n× This environment is externally managed\n╰─> To install Python packages system-wide, try apt install\n    python3-xyz, where xyz is the package you are trying to\n    install.\n    \n    If you wish to install a non-Debian-packaged Python package,\n    create a virtual environment using python3 -m venv path/to/venv.\n    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make\n    sure you have python3-full installed.\n    \n    If you wish to install a non-Debian packaged Python application,\n    it may be easiest to use pipx install xyz, which will manage a\n    virtual environment for you. Make sure you have pipx installed.\n    \n    See /usr/share/doc/python3.12/README.venv for more information.\n\nnote: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.\nhint: See PEP 668 for the detailed specification.\n"
}

PLAY RECAP ***********************************************************************************************
ansible-nas                : ok=35   changed=1    unreachable=0    failed=1    skipped=33   rescued=0    ignored=0   \\\

**Additional context**
Add any other context about the problem here.

New to reporting through GIT, please let me know what else I can provide.

**Comment by davestephens** [comment]
It has historically taken a little while for the dependent packages (Docker etc) to catch up with the LTS releases of Ubuntu. Because of that, I usually leave it a couple of months before upgrading, and I'm guessing you've uncovered something there. 

I haven't yet done **any** testing of Ubuntu 24.04. If you're keen to use Ansible-NAS, use 22.04 for now, which is still supported for another three years, and do an in-place upgrade in a few weeks once I've fixed the niggles 👍🏻

**Comment by vzoutenbier** [comment]
Thanks for the response!

I'll try downgrading-
but the weird thing is that I had this working 3 weeks ago using the same usb drive to flash ubuntu 24.04 on the same system.  I had a hardware short and had to replace a storage drive, and through it might have corrupted my os drive because I ran into this issue.  Something in the chain must have upgraded and made 24.04 incompatible :/ 

I'll go to 22.04.  Thanks!

**Comment by bobbbino** [comment]
I don't think this issue has been fixed because I'm doing exactly the same today and experiencing the same errors.

**Comment by davestephens** [comment]
Hi, I haven't done the work to move to 24.04 yet, real life has very much got in the way of any fun sort of development recently

**Comment by bobbbino** [comment]
Apologies dave. I didn't mean to be critical. You've given an amazing gift to the community with all this work that you've done! Ansible-nas is gamechanging!!

I just wanted to flag that this issue was not resolved because it was closed as completed back in May.

**Comment by tysaya123** [comment]
@bobbbino I ran into the same issue and didn't feel like downgrading my system just for this but I did find a workaround. Basically, what its asking us to do with the error is not use pip to install packages globally.

So by installing `virtualenv` when we install pip and creating a new `docker_venv` variable to use as the `virtualenv` the error message went away.

```
- name: Install python3-pip and virtualenv
  ansible.builtin.apt:
    name: python3-pip, virtualenv
    state: present
  register: result
  until: result is succeeded

- name: Remove docker-py python module
  ansible.builtin.pip:
    name: docker-py
    state: absent
    virtualenv: "{{ docker_venv }}"
  register: result
  until: result is succeeded

- name: Install docker python module
  ansible.builtin.pip:
    name: docker
    state: present
    virtualenv: "{{ docker_venv }}"
  register: result
  until: result is succeeded
```

**Comment by macabeast** [comment]
> [@bobbbino](https://github.com/bobbbino) I ran into the same issue and didn't feel like downgrading my system just for this but I did find a workaround. Basically, what its asking us to do with the error is not use pip to install packages globally.
> 
> So by installing `virtualenv` when we install pip and creating a new `docker_venv` variable to use as the `virtualenv` the error message went away.
> 
> ```
> - name: Install python3-pip and virtualenv
>   ansible.builtin.apt:
>     name: python3-pip, virtualenv
>     state: present
>   register: result
>   until: result is succeeded
> 
> - name: Remove docker-py python module
>   ansible.builtin.pip:
>     name: docker-py
>     state: absent
>     virtualenv: "{{ docker_venv }}"
>   register: result
>   until: result is succeeded
> 
> - name: Install docker python module
>   ansible.builtin.pip:
>     name: docker
>     state: present
>     virtualenv: "{{ docker_venv }}"
>   register: result
>   until: result is succeeded
> ```

Small note, had to add  "virtualenv_python: python3" in remove docker-py and install docker python. So it looked more like:

```
- name: Remove docker-py python module
  ansible.builtin.pip:
    name: docker-py
    state: absent
    virtualenv: "{{ docker_venv }}"
    virtualenv_python: python3
  register: result
  until: result is succeeded

- name: Install docker python module
  ansible.builtin.pip:
    name: docker
    state: present
    virtualenv: "{{ docker_venv }}"
    virtualenv_python: python3
  register: result
  until: result is succeeded
```
